databases:
  - name: unisaas-db
    plan: free
    databaseName: unisaas
    user: unisaas

services:
  - type: web
    name: unisaas-enterprise
    plan: free
    runtime: python
    buildCommand: "bash ./build.sh"
    startCommand: "gunicorn unisaas.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unisaas-db
          property: connectionURI
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: DJANGO_SETTINGS_MODULE
        value: "unisaas.settings.production"
      - key: WHITENOISE_MANIFEST_STRICT
        value: "false"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: TENANT_PARENT_DOMAINS
        sync: false
      - key: DJANGO_SUPERUSER_CREATE
        value: "false"
