# Generated by Django 6.0.4 on 2026-05-01 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(editable=False, max_length=255, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('university_admin', 'University Admin'), ('registration', 'Registration'), ('examination', 'Examination'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.university')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['university', 'email'], name='accounts_us_univers_8e9c3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('university', 'email'), name='unique_tenant_email')],
            },
        ),
    ]
