# Generated by Django 6.0.4 on 2026-05-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='application',
            name='entry_year',
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='admission_letters/'),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='application_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
