# Generated by Django 6.0.4 on 2026-05-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_course_options_academicyear_and_more'),
        ('admissions', '0002_remove_application_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academic.programme'),
        ),
    ]
