# Generated by Django 6.0.4 on 2026-05-01 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('letter_grade', models.CharField(max_length=5)),
                ('is_locked', models.BooleanField(default=False)),
                ('enrollment_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='registration.enrollmentcourse')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
