# Generated by Django 6.0.4 on 2026-05-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('registration', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='enrollment_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='registration.enrollmentcourse'),
        ),
        migrations.AddField(
            model_name='grade',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.university'),
        ),
    ]
